### PR TITLE
Add Chinese(Traditional) Language Support

### PR DESCRIPTION
**Pull request by Bob-YsPan**
I made some translation files base from the Traditional Chinese's version of 3D Pinball Resources that preinstalled in Chinese Version of Windows XP(And something translate by myself).

Maybe can merge into the future's version.

(Sorry I'm a newer of GitHub... so my repo have some redundant works)

### CODE REVIEW

**Comment by Bob-YsPan** [comment]
I try to decompline some apks and found that the folder name of Traditional Chinese maybe is "values-zh-rTW"

**Comment by Bob-YsPan** [comment]
I correct the folder names and little change the Translation(miss a little Translate)

**Comment by fexed** [comment]
Thank you very much!

**Comment by Bob-YsPan** [comment]
🙂

**Pull request merged**
